# Generated by Django 2.1.3 on 2019-05-11 13:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0032_auto_20190417_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_students',
            name='image',
            field=models.FileField(default='default.png', upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='list_students',
            name='birthdate',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 11, 18, 59, 52, 411578), help_text='Please specify english date: <em>YYYY-MM-DD</em>.'),
        ),
    ]
