# Generated by Django 2.1.3 on 2019-05-11 13:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0034_auto_20190511_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list_students',
            name='birthdate',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 11, 19, 5, 8, 9630), help_text='Please specify english date: <em>YYYY-MM-DD</em>.'),
        ),
    ]
