# Generated by Django 2.1.3 on 2019-05-13 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0036_auto_20190513_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list_students',
            name='birthdate',
            field=models.DateField(help_text='Please specify english date: <em>YYYY-MM-DD</em>.'),
        ),
    ]
