# Generated by Django 2.1.3 on 2019-05-16 10:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0038_auto_20190513_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list_students',
            name='birthdate',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 16, 16, 15, 37, 53979), help_text='Please specify english date: <em>YYYY-MM-DD</em>.'),
        ),
    ]
